### ISSUE TITLE
55-3 Sovelluksen UML:n mukainen luokkakaavio löytyy versionhallinnasta.

### ISSUE THREAD

**Issue by Maajoo** [SyntaxSynergy/.github#10]

**Comment by SophiaDun** [comment]
UML Luokkakaavio luotu, jossa näkyy yhteydet Tuote, tyyppi ja valmistaja tauluihin.
Yhteydet ovat tehty oikein ja loogisesti.
Kaavio löytyy .github repositorissa dokumentaatio kansiossa.
Hienoa työtä!
